files:
  accept:
  - "data/yara/**.yar"
  - "analyzer/windows/data/yara/**.yar"

false_positives:
  ignore:
  - rule: "CobaltStrikeBeacon"
  - rule: "Emotet"
  - rule: "NSIS"
  - rule: "UPX"
  - rule: "Syscall"
  - rule: "FormhookB"
