files:
  accept:
  - "data/yara/**.yar"
  - "analyzer/windows/data/yara/*.yar"

false_positives:
  ignore:
    - rule: "CobaltStrikeBeacon"
    - file: "analyzer/windows/data/yara/*"
      rule: "Blister"
