---
- name: Include KVM/QEMU tasks
  ansible.builtin.import_tasks: kvm_qemu/tasks/main.yml
  tags:
    - hypervisor
    - kvm_qemu

# Future: include libvirt tasks here
# - name: Include Libvirt tasks
#   ansible.builtin.import_tasks: libvirt/tasks/main.yml
#   tags:
#     - hypervisor
#     - libvirt
