---
- name: Include KVM/QEMU build tasks
  ansible.builtin.import_tasks: kvm_qemu/tasks/main.yml
  tags:
    - hypervisor
    - kvm_qemu

- name: Include SeaBIOS build tasks
  ansible.builtin.import_tasks: kvm_qemu/tasks/seabios.yml
  tags:
    - hypervisor
    - seabios

- name: Include libvirt build tasks
  ansible.builtin.import_tasks: libvirt/tasks/main.yml
  tags:
    - hypervisor
    - libvirt

- name: Include libvirt configuration tasks
  ansible.builtin.import_tasks: libvirt/tasks/configure.yml
  tags:
    - hypervisor
    - libvirt_config

- name: Include virbr1 network tasks
  ansible.builtin.import_tasks: libvirt/tasks/network.yml
  tags:
    - hypervisor
    - virbr1

- name: Include IOMMU tasks
  ansible.builtin.import_tasks: kvm_qemu/tasks/iommu.yml
  tags:
    - hypervisor
    - iommu

- name: Include VM creation tasks
  ansible.builtin.import_tasks: libvirt/tasks/vm_create.yml
  when: vm_autocreate | default(false) | bool
  tags:
    - hypervisor
    - vm_create
