---
apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
  name: analysis-policy
  annotations:
    description: syscalls + tracee security rules + extended default policy.
spec:
  scope:
    - comm=strace
    # - executable=/sh-shim
    - follow
  rules:
    # Signature-based events: https://github.com/aquasecurity/tracee/blob/main/examples/policies/signature_events.yaml- event: stdio_over_socket
    - event: k8s_api_connection
    - event: aslr_inspection
    - event: proc_mem_code_injection
    - event: docker_abuse   
    - event: scheduled_task_mod     
    - event: ld_preload     
    - event: cgroup_notify_on_release
    - event: default_loader_mod     
    - event: sudoers_modification   
    - event: sched_debug_recon      
    - event: system_request_key_mod 
    - event: cgroup_release_agent   
    - event: rcd_modification       
    - event: core_pattern_modification
    - event: proc_kcore_read
    - event: proc_mem_access
    - event: hidden_file_created    
    - event: anti_debugging 
    - event: ptrace_code_injection  
    - event: process_vm_write_inject
    - event: disk_mount     
    - event: dynamic_code_loading
    - event: fileless_execution     
    - event: illegitimate_shell     
    - event: kernel_module_loading  
    - event: k8s_cert_theft 
    #- event: proc_fops_hooking # problematic - somehow prevents syscall hooking signature from triggering
    - event: syscall_hooking
    - event: dropped_executable
    # ...
    - event: bpf_attach
    - event: cgroup_mkdir
    - event: cgroup_rmdir
    - event: container_create
    - event: container_remove
    - event: do_sigaction
    - event: file_modification
    #- event: format # faulty
    - event: ftrace_hook
    - event: hidden_kernel_module
    - event: hooked_syscall
    - event: kallsyms_lookup_name
    - event: magic_write
    - event: mem_prot_alert
    - event: net_tcp_connect
    - event: process_execute_failed
    - event: sched_process_exec
    - event: security_bpf_prog
    - event: security_bprm_check
    - event: security_file_mprotect
    - event: security_inode_unlink
    - event: security_sb_mount
    - event: security_socket_accept
    - event: security_socket_bind
    - event: security_socket_connect
    - event: security_socket_setsockopt
    - event: symbols_collision
    - event: symbols_loaded
    - event: vfs_read
    - event: vfs_readv
    # net events
    - event: net_packet_ipv4
    - event: net_packet_ipv6
    - event: net_packet_tcp
    - event: net_packet_udp
    - event: net_packet_icmp
    - event: net_packet_icmpv6
    - event: net_packet_dns
    #- event: net_packet_dns_request
    #- event: net_packet_dns_response
    - event: net_packet_http
    #- event: net_packet_http_request
    #- event: net_packet_http_response
    # syscalls
    - event: accept
    - event: accept4
    - event: access
    - event: acct
    - event: add_key
    - event: adjtimex
    - event: afs
    - event: afs_syscall
    - event: alarm
    - event: arch_prctl
    - event: bdflush
    - event: bind
    - event: bpf
    - event: break
    - event: brk
    - event: capget
    - event: capset
    - event: chdir
    - event: chmod
    - event: chown
    - event: chown16
    - event: chroot
    - event: clock_adjtime
    - event: clock_adjtime64
    - event: clock_getres
    - event: clock_getres_time32
    - event: clock_gettime
    - event: clock_gettime32
    - event: clock_nanosleep
    - event: clock_nanosleep_time32
    - event: clock_settime
    - event: clock_settime32
    - event: clone
    - event: clone3
    - event: close
    - event: close_range
    - event: connect
    - event: copy_file_range
    - event: creat
    - event: create_module
    - event: delete_module
    - event: dup
    - event: dup2
    - event: dup3
    - event: epoll_create
    - event: epoll_create1
    - event: epoll_ctl
    - event: epoll_ctl_old
    - event: epoll_pwait
    - event: epoll_pwait2
    - event: epoll_wait
    - event: epoll_wait_old
    - event: eventfd
    - event: eventfd2
    - event: execve
    - event: execveat
    - event: exit
    - event: exit_group
    - event: faccessat
    - event: faccessat2
    - event: fadvise64
    - event: fadvise64_64
    - event: fallocate
    - event: fanotify_init
    - event: fanotify_mark
    - event: fchdir
    - event: fchmod
    - event: fchmodat
    - event: fchown
    - event: fchown16
    - event: fchownat
    - event: fcntl
    - event: fcntl64
    - event: fdatasync
    - event: fgetxattr
    - event: finit_module
    - event: flistxattr
    - event: flock
    - event: fork
    - event: fremovexattr
    - event: fsconfig
    - event: fsetxattr
    - event: fsmount
    - event: fsopen
    - event: fspick
    - event: fstat
    - event: fstat64
    - event: fstatfs
    - event: fstatfs64
    - event: fsync
    - event: ftime
    - event: ftruncate
    - event: ftruncate64
    - event: futex
    - event: futex_time32
    - event: futimesat
    - event: get_kernel_syms
    - event: get_mempolicy
    - event: get_robust_list
    - event: get_thread_area
    - event: getcpu
    - event: getcwd
    - event: getdents
    - event: getdents64
    - event: getegid
    - event: getegid16
    - event: geteuid
    - event: geteuid16
    - event: getgid
    - event: getgid16
    - event: getgroups
    - event: getgroups16
    - event: getitimer
    - event: getpeername
    - event: getpgid
    - event: getpgrp
    - event: getpid
    - event: getpmsg
    - event: getppid
    - event: getpriority
    - event: getrandom
    - event: getresgid
    - event: getresgid16
    - event: getresuid
    - event: getresuid16
    - event: getrlimit
    - event: getrusage
    - event: getsid
    - event: getsockname
    - event: getsockopt
    - event: gettid
    - event: gettimeofday
    - event: getuid
    - event: getuid16
    - event: getxattr
    - event: gtty
    - event: idle
    - event: init_module
    - event: inotify_add_watch
    - event: inotify_init
    - event: inotify_init1
    - event: inotify_rm_watch
    - event: io_cancel
    - event: io_destroy
    - event: io_getevents
    - event: io_pgetevents
    - event: io_pgetevents_time32
    - event: io_setup
    - event: io_submit
    - event: io_uring_enter
    - event: io_uring_register
    - event: io_uring_setup
    - event: ioctl
    - event: ioperm
    - event: iopl
    - event: ioprio_get
    - event: ioprio_set
    - event: ipc
    - event: kcmp
    - event: kexec_file_load
    - event: kexec_load
    - event: keyctl
    - event: kill
    - event: landlock_add_rule
    - event: landlock_create_ruleset
    - event: landlock_restrict_self
    - event: lchown
    - event: lchown16
    - event: lgetxattr
    - event: link
    - event: linkat
    - event: listen
    - event: listxattr
    - event: llistxattr
    - event: llseek
    - event: lock
    - event: lookup_dcookie
    - event: lremovexattr
    - event: lseek
    - event: lsetxattr
    - event: lstat
    - event: lstat64
    - event: madvise
    - event: mbind
    - event: membarrier
    - event: memfd_create
    - event: memfd_secret
    - event: migrate_pages
    - event: mincore
    - event: mkdir
    - event: mkdirat
    - event: mknod
    - event: mknodat
    - event: mlock
    - event: mlock2
    - event: mlockall
    - event: mmap
    - event: mmap2
    - event: modify_ldt
    - event: mount
    - event: mount_setattr
    - event: move_mount
    - event: move_pages
    - event: mprotect
    - event: mpx
    - event: mq_getsetattr
    - event: mq_notify
    - event: mq_open
    - event: mq_timedreceive
    - event: mq_timedreceive_time32
    - event: mq_timedsend
    - event: mq_timedsend_time32
    - event: mq_unlink
    - event: mremap
    - event: msgctl
    - event: msgget
    - event: msgrcv
    - event: msgsnd
    - event: msync
    - event: munlock
    - event: munlockall
    - event: munmap
    - event: name_to_handle_at
    - event: nanosleep
    - event: newfstatat
    - event: nfsservctl
    - event: nice
    - event: old_getrlimit
    - event: old_select
    - event: oldfstat
    - event: oldlstat
    - event: oldolduname
    - event: oldstat
    - event: olduname
    - event: open
    - event: open_by_handle_at
    - event: open_tree
    - event: openat
    - event: openat2
    - event: pause
    - event: perf_event_open
    - event: personality
    - event: pidfd_getfd
    - event: pidfd_open
    - event: pidfd_send_signal
    - event: pipe
    - event: pipe2
    - event: pivot_root
    - event: pkey_alloc
    - event: pkey_free
    - event: pkey_mprotect
    - event: poll
    - event: ppoll
    - event: ppoll_time32
    - event: prctl
    - event: pread64
    - event: preadv
    - event: preadv2
    - event: prlimit64
    - event: process_madvise
    - event: process_mrelease
    - event: process_vm_readv
    - event: process_vm_writev
    - event: prof
    - event: profil
    - event: pselect6
    - event: pselect6_time32
    - event: ptrace
    - event: putpmsg
    - event: pwrite64
    - event: pwritev
    - event: pwritev2
    - event: query_module
    - event: quotactl
    - event: quotactl_fd
    - event: read
    - event: readahead
    - event: readdir
    - event: readlink
    - event: readlinkat
    - event: readv
    - event: reboot
    - event: recvfrom
    - event: recvmmsg
    - event: recvmmsg_time32
    - event: recvmsg
    - event: remap_file_pages
    - event: removexattr
    - event: rename
    - event: renameat
    - event: renameat2
    - event: request_key
    - event: restart_syscall
    - event: rmdir
    - event: rseq
    - event: rt_sigaction
    - event: rt_sigpending
    - event: rt_sigprocmask
    - event: rt_sigqueueinfo
    - event: rt_sigreturn
    - event: rt_sigsuspend
    - event: rt_sigtimedwait
    - event: rt_sigtimedwait_time32
    - event: rt_tgsigqueueinfo
    - event: sched_get_priority_max
    - event: sched_get_priority_min
    - event: sched_getaffinity
    - event: sched_getattr
    - event: sched_getparam
    - event: sched_getscheduler
    - event: sched_rr_get_interval
    - event: sched_rr_get_interval_time32
    - event: sched_setaffinity
    - event: sched_setattr
    - event: sched_setparam
    - event: sched_setscheduler
    - event: sched_yield
    - event: seccomp
    - event: security
    - event: select
    - event: semctl
    - event: semget
    - event: semop
    - event: semtimedop
    - event: sendfile
    - event: sendfile32
    - event: sendmmsg
    - event: sendmsg
    - event: sendto
    - event: set_mempolicy
    - event: set_robust_list
    - event: set_thread_area
    - event: set_tid_address
    - event: setdomainname
    - event: setfsgid
    - event: setfsgid16
    - event: setfsuid
    - event: setfsuid16
    - event: setgid
    - event: setgid16
    - event: setgroups
    - event: setgroups16
    - event: sethostname
    - event: setitimer
    - event: setns
    - event: setpgid
    - event: setpriority
    - event: setregid
    - event: setregid16
    - event: setresgid
    - event: setresgid16
    - event: setresuid
    - event: setresuid16
    - event: setreuid
    - event: setreuid16
    - event: setrlimit
    - event: setsid
    - event: setsockopt
    - event: settimeofday
    - event: setuid
    - event: setuid16
    - event: setxattr
    - event: sgetmask
    - event: shmat
    - event: shmctl
    - event: shmdt
    - event: shmget
    - event: shutdown
    - event: sigaction
    - event: sigaltstack
    - event: signal
    - event: signalfd
    - event: signalfd4
    - event: sigpending
    - event: sigprocmask
    - event: sigreturn
    - event: sigsuspend
    - event: socket
    - event: socketcall
    - event: socketpair
    - event: splice
    - event: ssetmask
    - event: stat
    - event: stat64
    - event: statfs
    - event: statfs64
    - event: statx
    - event: stime
    - event: stty
    - event: swapoff
    - event: swapon
    - event: symlink
    - event: symlinkat
    - event: sync
    - event: sync_file_range
    - event: syncfs
    - event: sysctl
    - event: sysfs
    - event: sysinfo
    - event: syslog
    - event: tee
    - event: tgkill
    - event: time
    - event: timer_create
    - event: timer_delete
    - event: timer_getoverrun
    - event: timer_gettime
    - event: timer_gettime32
    - event: timer_settime
    - event: timer_settime32
    - event: timerfd_create
    - event: timerfd_gettime
    - event: timerfd_gettime32
    - event: timerfd_settime
    - event: timerfd_settime32
    - event: times
    - event: tkill
    - event: truncate
    - event: truncate64
    - event: tuxcall
    - event: ulimit
    - event: umask
    - event: umount
    - event: umount2
    - event: uname
    - event: unlink
    - event: unlinkat
    - event: unshare
    - event: uselib
    - event: userfaultfd
    - event: ustat
    - event: utime
    - event: utimensat
    - event: utimensat_time32
    - event: utimes
    - event: vfork
    - event: vhangup
    - event: vm86
    - event: vm86old
    - event: vmsplice
    - event: vserver
    - event: wait4
    - event: waitid
    - event: waitpid
    - event: write
    - event: writev
