# Copyright (C) 2010-2015 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file 'docs/LICENSE' for copying permission.

"""add filename to tasks

Revision ID: fd50efe2ab14
Revises: 8537286ff4d5
Create Date: 2021-12-31 08:59:12.774006

"""

# revision identifiers, used by Alembic.
revision = 'fd50efe2ab14'
down_revision = '8537286ff4d5'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('filename', sa.Text(), nullable=False, server_default="None"))
    op.alter_column("tasks", "filename", server_default="None")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'filename')
    # ### end Alembic commands ###
