# Generated by Django 4.1 on 2022-11-24 08:39
# https://realpython.com/django-migrations-a-primer/

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reports",
            field=models.BooleanField(default=False),
        ),
    ]
