<#
.SYNOPSIS
    CAPEv2 agent deploy script (PowerShell)
    Generated by Ansible — 2026-07-26T01:35:12Z
.DESCRIPTION
    Copies agent.py to the guest, registers it as a Windows service,
    and tests connectivity to the result server.
#>

Write-Output "=== CAPEv2 Agent Deployment ==="

$agentSource = ".\agent.py"
$agentDest = "C:\ProgramData\cape\agent.py"
$serviceName = "CAPEAgent"

# Create destination directory
if (-not (Test-Path "C:\ProgramData\cape")) {
    New-Item -ItemType Directory -Path "C:\ProgramData\cape" -Force
}

# Copy agent
if (Test-Path $agentSource) {
    Copy-Item -Path $agentSource -Destination $agentDest -Force
    Write-Output "Agent copied to $agentDest"
} else {
    Write-Error "agent.py not found at $agentSource. Copy agent.py from the CAPEv2 host before running this script."
    exit 1
}

# Check if service already exists
$existing = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Output "Service $serviceName already exists. Restarting..."
    Restart-Service -Name $serviceName
} else {
    # Create service
    New-Service -Name $serviceName -BinaryPathName "python.exe $agentDest" -DisplayName "CAPEv2 Agent" -StartupType Automatic
    Write-Output "Service $serviceName created."
    Start-Service -Name $serviceName
}

# Test connectivity
Write-Output "Testing connectivity to 192.168.1.1:8000..."
try {
    $tcp = New-Object System.Net.Sockets.TcpClient
    $tcp.Connect("192.168.1.1", 8000)
    Write-Output "Connection OK!"
    $tcp.Close()
} catch {
    Write-Error "Cannot connect to 192.168.1.1:8000. Check that the result server is running."
}

Write-Output "Agent deployment complete."
