<#
.SYNOPSIS
    CAPEv2 guest VM hardening script (PowerShell)
    Generated by Ansible — 2026-07-26T01:35:12Z
.DESCRIPTION
    Disables Windows Defender, Firewall, SmartScreen, telemetry,
    scheduled tasks, and other noisy services.
#>

Write-Output "=== CAPEv2 Guest Hardening (PowerShell) ==="

Write-Output "Disabling Windows Defender..."
New-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender" -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force
Set-MpPreference -DisableRealtimeMonitoring $true -DisableBehaviorMonitoring $true -DisableIOAVProtection $true -DisableIntrusionPreventionSystem $true -DisableScriptScanning $true -DisableRemovableDriveScanning $true -EnableControlledFolderAccess Disabled -EnableNetworkProtection AuditMode -Force -MAPSReporting Disabled -SubmitSamplesConsent NeverSend

Write-Output "Disabling Windows Firewall..."
Set-NetFirewallProfile -Profile Domain, Public, Private -Enabled False

Write-Output "Disabling SmartScreen..."
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "EnableSmartScreen" -Type DWord -Value 0
If (!(Test-Path "HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter")) {
    New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter" -Force | Out-Null
}
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter" -Name "EnabledV9" -Type DWord -Value 0

Write-Output "Disabling telemetry..."
New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Force
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" "AllowTelemetry" 0

Write-Output "Disabling scheduled telemetry tasks..."
$tasks = @(
    "\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
    "\Microsoft\Windows\Application Experience\ProgramDataUpdater",
    "\Microsoft\Windows\Application Experience\StartupAppTask",
    "\Microsoft\Windows\Application Experience\PcaPatchDbTask"
)
foreach ($task in $tasks) {
   Disable-ScheduledTask -TaskName $task
}

Write-Output "Hardening complete. A reboot is recommended."
