@echo off
REM CAPEv2 guest VM hardening script (Batch)
REM Generated by Ansible — 2026-07-26T01:35:12Z

echo === CAPEv2 Guest Hardening (Batch) ===

REM Disable UAC
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v EnableLUA /t REG_DWORD /d 0 /f

REM Disable Windows Defender
sc config WinDefend start= disabled

REM Disable Windows Update
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update" /v AUOptions /t REG_DWORD /d 1 /f

REM Disable firewall
netsh advfirewall set allprofiles state off

REM Disable IPv6
netsh interface teredo set state disabled
netsh interface ipv6 6to4 set state state=disabled undoonstop=disabled
netsh interface ipv6 isatap set state state=disabled

REM Disable NetBIOS
reg add "HKLM\SYSTEM\CurrentControlSet\services\Lmhosts" /v Start /t REG_DWORD /d 4 /f

REM Disable LLMNR
reg add "HKLM\Software\policies\Microsoft\Windows NT\DNSClient" /v "EnableMulticast" /t REG_DWORD /d 0 /f

REM Disable telemetry
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
sc stop DiagTrack
sc config DiagTrack start= disabled
sc stop dmwappushservice
sc config dmwappushservice start= disabled

REM Disable monitor timeout
POWERCFG -CHANGE -monitor-timeout-ac 0
POWERCFG -CHANGE -monitor-timeout-dc 0

echo Hardening complete. A reboot is recommended.
