<#
.SYNOPSIS
    CAPEv2 guest VM dependency installer (PowerShell)
    Generated by Ansible — 2026-07-26T01:35:12Z
.DESCRIPTION
    Installs Python, VC++ redistributable, and Python packages
    required by the CAPE agent.
#>

Write-Output "=== CAPEv2 Guest Dependency Installer ==="

# Check if Python is installed
$pyInstalled = $false
try {
    $pyVersion = python --version 2>&1
    if ($pyVersion -match "3.11.4") {
        $pyInstalled = $true
        Write-Output "Python 3.11.4 already installed."
    } else {
        Write-Output "Python version mismatch: $pyVersion"
    }
} catch {
    Write-Output "Python not found."
}

if (-not $pyInstalled) {
    Write-Output "Downloading Python 3.11.4..."
    $url = "https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe"
    $out = "$env:TEMP\python-installer.exe"
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $url -OutFile $out
    Write-Output "Installing Python 3.11.4..."
    Start-Process -Wait -FilePath $out -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0"
}

Write-Output "Installing pip packages..."
pip3 install pillow pywintrace

Write-Output "Dependency installation complete."
