<#
.SYNOPSIS
    CAPEv2 agent uninstall script (PowerShell)
    Generated by Ansible — 2026-07-26T01:35:12Z
.DESCRIPTION
    Stops and removes the CAPE agent service and cleans up files.
#>

Write-Output "=== CAPEv2 Agent Uninstall ==="

$serviceName = "CAPEAgent"

$existing = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Output "Stopping service $serviceName..."
    Stop-Service -Name $serviceName -Force
    sc.exe delete $serviceName
    Write-Output "Service $serviceName removed."
}

$agentDest = "C:\ProgramData\cape\agent.py"
if (Test-Path $agentDest) {
    Remove-Item -Path $agentDest -Force
    Write-Output "Removed $agentDest."
}

Write-Output "Agent uninstall complete."
