# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: capemon_pb.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'capemon_pb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61pemon_pb.proto\x12\x07\x63\x61pemon\"*\n\x0c\x41rgumentInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"a\n\x0bInfoMessage\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12#\n\x04\x61rgs\x18\x04 \x03(\x0b\x32\x15.capemon.ArgumentInfo\"\xbd\x01\n\x0b\x43\x61llMessage\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\tthread_id\x18\x02 \x01(\x05\x12\x16\n\x0ereturn_address\x18\x03 \x01(\x04\x12\x1d\n\x15parent_return_address\x18\x04 \x01(\x04\x12\x12\n\nis_success\x18\x05 \x01(\x08\x12\x0e\n\x06retval\x18\x06 \x01(\x04\x12\x11\n\targuments\x18\x07 \x03(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x04\x12\x0b\n\x03\x61ux\x18\t \x03(\t\"f\n\x0eProcessMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12\x0c\n\x04ppid\x18\x03 \x01(\x05\x12\x13\n\x0bmodule_path\x18\x04 \x01(\t\x12\x11\n\tproc_name\x18\x05 \x01(\t\"\x1f\n\x0c\x44\x65\x62ugMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xba\x01\n\tHookEvent\x12$\n\x04info\x18\x01 \x01(\x0b\x32\x14.capemon.InfoMessageH\x00\x12$\n\x04\x63\x61ll\x18\x02 \x01(\x0b\x32\x14.capemon.CallMessageH\x00\x12.\n\x0bnew_process\x18\x03 \x01(\x0b\x32\x17.capemon.ProcessMessageH\x00\x12&\n\x05\x64\x65\x62ug\x18\x04 \x01(\x0b\x32\x15.capemon.DebugMessageH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capemon_pb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARGUMENTINFO']._serialized_start=29
  _globals['_ARGUMENTINFO']._serialized_end=71
  _globals['_INFOMESSAGE']._serialized_start=73
  _globals['_INFOMESSAGE']._serialized_end=170
  _globals['_CALLMESSAGE']._serialized_start=173
  _globals['_CALLMESSAGE']._serialized_end=362
  _globals['_PROCESSMESSAGE']._serialized_start=364
  _globals['_PROCESSMESSAGE']._serialized_end=466
  _globals['_DEBUGMESSAGE']._serialized_start=468
  _globals['_DEBUGMESSAGE']._serialized_end=499
  _globals['_HOOKEVENT']._serialized_start=502
  _globals['_HOOKEVENT']._serialized_end=688
# @@protoc_insertion_point(module_scope)
