rule Formbook {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2018-11-23"
        version = "1"
        description = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator 0.1a"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.formbook"
        malpedia_version = "20180607"
        malpedia_license = "CC BY-NC-SA 4.0"
        malpedia_sharing = "TLP:WHITE"
        cape_type = "Formbook Payload"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using yara-signator.
     * The code and documentation / approach will be published in the near future here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */

    strings:
        $sequence_0 = { 03c8 0f31 2bc1 8945fc }
            // n = 4, score = 6000
            //   03c8                 | add                 ecx, eax
            //   0f31                 | rdtsc               
            //   2bc1                 | sub                 eax, ecx
            //   8945fc               | mov                 dword ptr [ebp - 4], eax

        $sequence_1 = { 3c24 0f8476ffffff 3c25 7494 }
            // n = 4, score = 6000
            //   3c24                 | cmp                 al, 0x24
            //   0f8476ffffff         | je                  0x112a53
            //   3c25                 | cmp                 al, 0x25
            //   7494                 | je                  0x112a75

        $sequence_2 = { 3b4f14 7395 85c9 7491 }
            // n = 4, score = 6000
            //   3b4f14               | cmp                 ecx, dword ptr [edi + 0x14]
            //   7395                 | jae                 0x11255b
            //   85c9                 | test                ecx, ecx
            //   7491                 | je                  0x11255b

        $sequence_3 = { 3c69 7544 8b7d18 8b0f }
            // n = 4, score = 6000
            //   3c69                 | cmp                 al, 0x69
            //   7544                 | jne                 0x112c1f
            //   8b7d18               | mov                 edi, dword ptr [ebp + 0x18]
            //   8b0f                 | mov                 ecx, dword ptr [edi]

        $sequence_4 = { 5d c3 8d507c 80fa07 }
            // n = 4, score = 6000
            //   5d                   | pop                 ebp
            //   c3                   | ret                 
            //   8d507c               | lea                 edx, dword ptr [eax + 0x7c]
            //   80fa07               | cmp                 dl, 7

        $sequence_5 = { 0fbe5c0e01 0fb6540e02 83e30f c1ea06 }
            // n = 4, score = 6000
            //   0fbe5c0e01           | movsx               ebx, byte ptr [esi + ecx + 1]
            //   0fb6540e02           | movzx               edx, byte ptr [esi + ecx + 2]
            //   83e30f               | and                 ebx, 0xf
            //   c1ea06               | shr                 edx, 6

        $sequence_6 = { 57 8945fc 8945f4 8945f8 }
            // n = 4, score = 6000
            //   57                   | push                edi
            //   8945fc               | mov                 dword ptr [ebp - 4], eax
            //   8945f4               | mov                 dword ptr [ebp - 0xc], eax
            //   8945f8               | mov                 dword ptr [ebp - 8], eax

        $sequence_7 = { 66890c02 5b 8be5 5d }
            // n = 4, score = 6000
            //   66890c02             | mov                 word ptr [edx + eax], cx
            //   5b                   | pop                 ebx
            //   8be5                 | mov                 esp, ebp
            //   5d                   | pop                 ebp

        $sequence_8 = { 3c54 7404 3c74 75f4 }
            // n = 4, score = 6000
            //   3c54                 | cmp                 al, 0x54
            //   7404                 | je                  0x117e2f
            //   3c74                 | cmp                 al, 0x74
            //   75f4                 | jne                 0x117e23

        $sequence_9 = { 56 6803010000 8d8595feffff 6a00 }
            // n = 4, score = 6000
            //   56                   | push                esi
            //   6803010000           | push                0x103
            //   8d8595feffff         | lea                 eax, dword ptr [ebp - 0x16b]
            //   6a00                 | push                0

    condition:
        7 of them
}