#!/usr/bin/env python
# Copyright (C) 2010-2015 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file 'docs/LICENSE' for copying permission.
import argparse
import functools
import gc
import json
import logging
import os
import platform
import resource
import signal
import sys
from contextlib import suppress

log = logging.getLogger()

try:
    from setproctitle import getproctitle, setproctitle
except ImportError:
    log.critical("Missed setproctitle dependency. Run: poetry install")
    sys.exit(1)

if sys.version_info[:2] < (3, 8):
    log.critical("You are running an incompatible version of Python, please use >= 3.8")
    sys.exit(1)

try:
    import pebble  # noqa: F401  # fail fast with a clear message if the dep is missing (engines import it)
except ImportError:
    log.critical("Missed pebble dependency. Run: poetry install")
    sys.exit(1)

sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)), ".."))

from lib.cuckoo.common.config import Config
from lib.cuckoo.common.constants import CUCKOO_ROOT
from lib.cuckoo.common.path_utils import path_delete, path_exists, path_mkdir
from lib.cuckoo.common.utils import get_options, option_dict_enabled
from lib.cuckoo.core.database import Database, init_database
from lib.cuckoo.core.data.task import (
    TASK_FAILED_REPORTING,
    TASK_REPORTED
)
from lib.cuckoo.core.plugins import RunProcessing, RunReporting, RunSignatures
from lib.cuckoo.core.startup import ConsoleHandler, check_linux_dist, init_modules

cfg = Config()
logconf = Config("logging")
repconf = Config("reporting")
db = Database()

if repconf.mongodb.enabled:
    from bson.objectid import ObjectId

    from dev_utils.mongodb import mongo_find, mongo_find_one

if repconf.elasticsearchdb.enabled and not repconf.elasticsearchdb.searchonly:
    from elasticsearch.exceptions import RequestError as ESRequestError

    from dev_utils.elasticsearchdb import elastic_handler, get_analysis_index, get_query_by_info_id

    es = elastic_handler

check_linux_dist()

original_proctitle = getproctitle()


# https://stackoverflow.com/questions/41105733/limit-ram-usage-to-python-program
def memory_limit(percentage: float = 0.8):
    """
    Sets a memory limit for the current process on Linux systems.

    Args:
        percentage (float): Percentage of the total system memory that is allowed to be used. Defaults to 0.8 (80%).

    Returns:
        None
    """
    if platform.system() != "Linux":
        log.debug("Only works on linux!")
        return
    _, hard = resource.getrlimit(resource.RLIMIT_AS)
    resource.setrlimit(resource.RLIMIT_AS, (int(get_memory() * 1024 * percentage), hard))


def get_memory():
    with open("/proc/meminfo", "r") as mem:
        free_memory = 0
        for i in mem:
            sline = i.split()
            if str(sline[0]) == "MemAvailable:":
                free_memory = int(sline[1])
                break
    return free_memory


def process(
    target=None,
    sample_sha256=None,
    task=None,
    report=False,
    auto=False,
    capeproc=False,
    memory_debugging=False,
    debug: bool = False,
):
    # This is the results container. It's what will be used by all the
    # reporting modules to make it consumable by humans and machines.
    # It will contain all the results generated by every processing
    # module available. Its structure can be observed through the JSON
    # dump in the analysis' reports folder. (If jsondump is enabled.)

    task_dict = task.to_dict() or {}
    task_id = task_dict.get("id") or 0
    task_options = get_options(task_dict.get("options"))
    task_dict["_options_parsed"] = task_options
    # cluster mode
    main_task_id = task_options.get("main_task_id", 0) if "main_task_id" in task_options else False

    # ToDo new logger here
    per_analysis_handler = init_per_analysis_logging(tid=str(task_id), debug=debug)
    set_formatter_fmt(task_id, main_task_id)
    setproctitle(f"{original_proctitle} [Task {task_id}]")
    results = {"statistics": {"processing": [], "signatures": [], "reporting": []}}
    try:
        minproc = option_dict_enabled(task_options, "minproc")
        if memory_debugging:
            gc.collect()
            log.info("(1) GC object counts: %d, %d", len(gc.get_objects()), len(gc.garbage))
        if memory_debugging:
            gc.collect()
            log.info("(2) GC object counts: %d, %d", len(gc.get_objects()), len(gc.garbage))
        with db.session.begin():
            RunProcessing(task=task_dict, results=results).run()
        if memory_debugging:
            gc.collect()
            log.info("(3) GC object counts: %d, %d", len(gc.get_objects()), len(gc.garbage))

        if not minproc:
            RunSignatures(task=task_dict, results=results).run()
        else:
            log.info("minproc enabled for task %s: skipping signatures", task_id)
        if memory_debugging:
            gc.collect()
            log.info("(4) GC object counts: %d, %d", len(gc.get_objects()), len(gc.garbage))

        if report:
            if auto or capeproc:
                reprocess = False
            else:
                reprocess = report

            error_count = RunReporting(task=task.to_dict(), results=results, reprocess=reprocess).run()
            status = TASK_REPORTED if error_count == 0 else TASK_FAILED_REPORTING
            with db.session.begin():
                db.set_status(task_id, status)

            if auto:
                # Is ok to delete original file, but we need to lookup on delete_bin_copy if no more pendings tasks
                if cfg.cuckoo.delete_original and target and path_exists(target):
                    path_delete(target)

                if cfg.cuckoo.delete_bin_copy and task.category != "url":
                    copy_path = os.path.join(CUCKOO_ROOT, "storage", "binaries", sample_sha256)
                    if path_exists(copy_path):
                        with db.session.begin():
                            is_still_used = db.sample_still_used(sample_sha256, task_id)
                        if not is_still_used:
                            path_delete(copy_path)

        if memory_debugging:
            gc.collect()
            log.info("(5) GC object counts: %d, %d", len(gc.get_objects()), len(gc.garbage))
            for i, obj in enumerate(gc.garbage):
                log.info("(garbage) GC object #%d: type=%s", i, type(obj).__name__)
    finally:
        per_analysis_handler.close()
        log.removeHandler(per_analysis_handler)

        # Remove the SQLAlchemy session to ensure the next task pulls objects from
        # the database, instead of relying on a potentially outdated object cache.
        # Stale data can prevent SQLAlchemy from querying the database or issuing
        # statements, resulting in unexpected errors and inconsistencies.
        db.session.remove()


def run_task(task, memory_debugging=False, debug=False):
    """Run exactly one completed task to completion (processing -> report).
    Extracted from autoprocess so every engine shares identical per-task setup."""
    sample_hash = ""
    if task.category != "url":
        with db.session.begin():
            sample = db.view_sample(task.sample_id)
            if sample:
                sample_hash = sample.sha256
    try:
        process(
            task.target,
            sample_hash,
            report=True,
            auto=True,
            task=task,
            memory_debugging=memory_debugging,
            debug=debug,
        )
    finally:
        set_formatter_fmt()
        setproctitle(original_proctitle)


def init_worker():
    signal.signal(signal.SIGINT, signal.SIG_IGN)
    # See https://docs.sqlalchemy.org/en/14/core/pooling.html#using-connection-pools-with-multiprocessing-or-os-fork
    db.engine.dispose(close=False)

    # Avoid fork deadlock: use direct list ops instead of
    # handler.close()/removeHandler()/addHandler() which acquire locks.
    # Inherited FDs are intentionally leaked after fork.
    log.handlers[:] = []

    # Restore Console Handler (no lock-acquiring addHandler)
    ch = ConsoleHandler()
    ch.setFormatter(FORMATTER)
    log.handlers.append(ch)

    # Eagerly compile the YARA ruleset once per worker so the first task
    # this worker picks up doesn't pay the ~3s compile cost. The result
    # is cached on the File class for the worker's lifetime; init_yara()
    # is idempotent (no-op when already initialized) so this is safe to
    # call here even if some downstream code path also calls it.
    try:
        from lib.cuckoo.common.objects import File
        File.init_yara()
    except Exception:
        log.debug("worker init: yara pre-compile skipped", exc_info=True)

    # Restore Syslog Handler if enabled
    if logconf.logger.syslog_process:
        try:
            slh = logging.handlers.SysLogHandler(address=logconf.logger.syslog_dev)
            slh.setFormatter(FORMATTER)
            log.addHandler(slh)
        except Exception as e:
            log.warning("Failed to restore Syslog handler in worker: %s", e)

    # Restore File Handler using WatchedFileHandler to support rotation
    try:
        path = os.path.join(CUCKOO_ROOT, "log", "process.log")
        fh = logging.handlers.WatchedFileHandler(path)
        fh.setFormatter(FORMATTER)
        log.addHandler(fh)
    except PermissionError as e:
        log.warning("Failed to restore File handler in worker due to permissions: %s", e)


def get_formatter_fmt(task_id=None, main_task_id=None):
    """
    Generates a logging format string with optional task identifiers.

    Args:
        task_id (int, optional): The ID of the task. Defaults to None.
        main_task_id (int, optional): The ID of the main task. Defaults to None.

    Returns:
        str: A formatted string for logging that includes the task information if provided.
    """
    task_info = f"[Task {task_id}" if task_id is not None else ""
    if main_task_id:
        task_info += f" ({main_task_id})"
    if task_id or main_task_id:
        task_info += "] "
    return f"%(asctime)s {task_info}[%(name)s] %(levelname)s: %(message)s"


FORMATTER = logging.Formatter(get_formatter_fmt())


def set_formatter_fmt(task_id=None, main_task_id=None):
    FORMATTER._style._fmt = get_formatter_fmt(task_id, main_task_id)


class ForceClosingTimedRotatingFileHandler(logging.handlers.TimedRotatingFileHandler):
    def doRollover(self):
        """
        Override doRollover to force close the old handler before creating a new one.
        """
        if self.stream:
            self.stream.flush()
            self.stream.close()
        super().doRollover()


def init_logging(debug=False):
    """
    Initializes logging for the application.

    This function sets up logging handlers for console output, syslog, and file output.
    It also configures log rotation if enabled in the configuration.

    Args:
        debug (bool): If True, sets the logging level to DEBUG. Otherwise, sets it to INFO.

    Returns:
        tuple: A tuple containing the console handler, file handler, and syslog handler (if configured).

    Raises:
        PermissionError: If there is an issue creating or accessing the log file, typically due to incorrect user permissions.
    # Pyattck creates root logger which we don't want. So we must use this dirty hack to remove it
    # If basicConfig was already called by something and had a StreamHandler added,
    # replace it with a ConsoleHandler.
    for h in log.handlers[:]:
        if isinstance(h, logging.StreamHandler) and h.stream == sys.stderr:
            log.removeHandler(h)
            h.close()
    """
    """
    Handlers:
        - ch - console handler
        - slh - syslog handler
        - fh - file handle -> process.log
    """

    ch = ConsoleHandler()
    ch.setFormatter(FORMATTER)
    log.addHandler(ch)

    slh = False

    if logconf.logger.syslog_process:
        slh = logging.handlers.SysLogHandler(address=logconf.logger.syslog_dev)
        slh.setFormatter(FORMATTER)
        log.addHandler(slh)

    try:
        if not path_exists(os.path.join(CUCKOO_ROOT, "log")):
            path_mkdir(os.path.join(CUCKOO_ROOT, "log"))

        path = os.path.join(CUCKOO_ROOT, "log", "process.log")
        if logconf.log_rotation.enabled:
            days = logconf.log_rotation.backup_count or 7
            fh = ForceClosingTimedRotatingFileHandler(path, when="midnight", backupCount=int(days))
        else:
            fh = logging.handlers.WatchedFileHandler(path)

        fh.setFormatter(FORMATTER)
        log.addHandler(fh)
    except PermissionError:
        log.critical("PermissionError to create/access log. Probably executed with wrong user.")
        sys.exit(1)

    if debug:
        log.setLevel(logging.DEBUG)
    else:
        log.setLevel(logging.INFO)

    logging.getLogger("urllib3").setLevel(logging.WARNING)
    return ch, fh, slh


def init_per_analysis_logging(tid=0, debug=False):
    """
    Handlers:
        - fhpa - file handler per analysis
    """

    fhpa = False

    try:
        if not path_exists(os.path.join(CUCKOO_ROOT, "log")):
            path_mkdir(os.path.join(CUCKOO_ROOT, "log"))

        if logconf.logger.process_analysis_folder:
            path = os.path.join(CUCKOO_ROOT, "storage", "analyses", str(tid), "process.log")
        else:
            path = os.path.join(CUCKOO_ROOT, "log", "process-%s.log" % str(tid))
        if path_exists(path):
            path_delete(path)

        fhpa = logging.handlers.WatchedFileHandler(path)
        fhpa.setFormatter(FORMATTER)
        log.addHandler(fhpa)
    except PermissionError:
        log.critical("PermissionError to create/access log. Probably executed with wrong user.")
        sys.exit(1)

    if debug:
        log.setLevel(logging.DEBUG)
    else:
        log.setLevel(logging.INFO)

    return fhpa



def autoprocess(
    parallel=1,
    failed_processing=False,
    maxtasksperchild=7,
    memory_debugging=False,
    processing_timeout=300,
    debug: bool = False,
    disable_memory_limit: bool = False,
    engine: str = "pebble",
):
    """
    Automatically processes analysis data using a process pool engine.

    Args:
        parallel (int): Number of parallel processes to use. Default is 1.
        failed_processing (bool): Whether to process failed tasks. Default is False.
        maxtasksperchild (int): Maximum number of tasks per child process (pebble engine only).
            Default is 7. Pass 0 to disable worker recycling (avoids deadlock on some systems).
        memory_debugging (bool): Whether to enable memory debugging. Default is False.
        processing_timeout (int): Timeout for processing each task in seconds. Default is 300.
        debug (bool): Whether to enable debug mode. Default is False.
        disable_memory_limit (bool): Skip setting process memory limits. Default is False.
        engine (str): Processing engine to use: "pebble" (default) or "prefork".

    Raises:
        KeyboardInterrupt: If the process is interrupted by the user.
        MemoryError: If there is not enough free RAM to run processing.
        OSError: If an OS-related error occurs.
        Exception: If any other exception occurs during processing.
    """
    from lib.cuckoo.core.processing_engine import get_engine
    from lib.cuckoo.core.processing_engine.source import TaskSource

    if not disable_memory_limit:
        memory_limit()
    log.info("Processing analysis data (engine=%s)", engine)

    # Compile the YARA ruleset ONCE in the supervisor, before the engine forks any
    # workers. Every forked child then inherits the compiled rules via copy-on-write
    # fork (0s + shared read-only pages), and its init_worker() File.init_yara() call
    # short-circuits on the idempotency guard. Without this, prefork — which forks a
    # fresh child per task — would pay the ~3s compile on every single task. Safe to
    # call here: compilation is single-threaded, so it does not break the prefork
    # single-threaded-before-fork invariant.
    from lib.cuckoo.common.objects import File

    File.init_yara()

    source = TaskSource(db, failed_processing=failed_processing)
    eng = get_engine(
        engine,
        task_fn=functools.partial(run_task, memory_debugging=memory_debugging, debug=debug),
        worker_init=init_worker,
        source=source,
        parallel=parallel,
        timeout=processing_timeout,
    )
    eng.max_count = cfg.cuckoo.max_analysis_count
    if engine == "pebble":
        eng.max_tasks = maxtasksperchild
    eng.run()


def _load_report(task_id: int):
    """
    Load the analysis report for a given task ID from the configured database.

    This function attempts to load the analysis report from MongoDB if it is enabled.
    If MongoDB is not enabled, it tries to load the report from Elasticsearch if it is enabled and not in search-only mode.

    Args:
        task_id (int): The ID of the task for which to load the analysis report.

    Returns:
        dict or bool: The analysis report as a dictionary if found, otherwise False.
    """
    if repconf.mongodb.enabled:
        analysis = mongo_find_one("analysis", {"info.id": task_id}, sort=[("_id", -1)])
        for process in analysis.get("behavior", {}).get("processes", []):
            calls = [ObjectId(call) for call in process["calls"]]
            process["calls"] = []
            for call in mongo_find("calls", {"_id": {"$in": calls}}, sort=[("_id", 1)]) or []:
                process["calls"] += call["calls"]
        return analysis

    if repconf.elasticsearchdb.enabled and not repconf.elasticsearchdb.searchonly:
        try:
            analyses = (
                es.search(index=get_analysis_index(), query=get_query_by_info_id(task_id), sort={"info.id": {"order": "desc"}})
                .get("hits", {})
                .get("hits", [])
            )
            if analyses:
                return analyses[0]
        except ESRequestError as e:
            log.error(e)

    return False


def str_to_bool(v):
    if isinstance(v, bool):
        return v
    if isinstance(v, str):
        return v.lower() in ("yes", "true", "t", "y", "1")
    return False


def parse_id(id_string: str):
    """
    Parses a string representing a range or list of ranges of IDs and returns a list of tuples.

    Args:
        id_string (str): A string representing IDs. It can be "auto" or a string of comma-separated
            ranges (e.g., "1-3,5,7-9").

    Returns:
        list: A list of tuples where each tuple represents a range of IDs. If the input is "auto",
            it returns the string "auto".

    Raises:
        TypeError: If the input string is not in the correct format or if a range is invalid.
    """
    if id_string == "auto":
        return id_string
    id_string = id_string.replace(" ", "")
    blocks = [block.split("-") for block in id_string.split(",")]
    for index, block in enumerate(blocks):
        block = list(map(int, block))
        if len(block) == 2:
            if block[1] < block[0]:
                raise TypeError("Invalid id input")
            else:
                blocks[index] = block
        elif len(block) == 1:
            blocks[index] = (block[0], block[0])
        else:
            raise TypeError("Invalid id input")
    return blocks


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "id",
        type=parse_id,
        help="ID of the analysis to process (auto for continuous processing of unprocessed tasks). Can be 1 or 1-10 or 1,3,5,7",
        default=os.getenv("CAPE_ID") or "auto",
        nargs="?",
    )
    parser.add_argument("-c", "--caperesubmit", help="Allow CAPE resubmit processing.", action="store_true", required=False)
    parser.add_argument(
        "-d",
        "--debug",
        help="Display debug messages",
        action="store_true",
        required=False,
        default=str_to_bool(os.getenv("CAPE_DEBUG", "false")),
    )
    parser.add_argument("-r", "--report", help="Re-generate report", action="store_true", required=False)
    parser.add_argument(
        "-p",
        "--parallel",
        help="Number of parallel threads to use (auto mode only).",
        type=int,
        required=False,
        default=int(os.getenv("CAPE_PARALLEL") or 1),
    )
    parser.add_argument(
        "-fp",
        "--failed-processing",
        help="reprocess failed processing",
        action="store_true",
        required=False,
        default=str_to_bool(os.getenv("CAPE_FAILED_PROCESSING", "false")),
    )
    parser.add_argument(
        "-mc",
        "--maxtasksperchild",
        help="Max children tasks per worker",
        action="store",
        type=int,
        required=False,
        default=int(os.getenv("CAPE_MAXTASKSPERCHILD") or 7),
    )
    parser.add_argument(
        "-md",
        "--memory-debugging",
        help="Enable logging garbage collection related info",
        action="store_true",
        required=False,
        default=str_to_bool(os.getenv("CAPE_MEMORY_DEBUGGING", "false")),
    )
    parser.add_argument(
        "-pt",
        "--processing-timeout",
        help="Max amount of time spent in processing before we fail a task",
        action="store",
        type=int,
        required=False,
        default=int(os.getenv("CAPE_PROCESSING_TIMEOUT") or 300),
    )
    testing_args = parser.add_argument_group("Signature testing options")
    testing_args.add_argument(
        "-sig",
        "--signatures",
        help="Re-execute signatures on the report, doesn't work for signature with self.get_raw_argument, use self.get_argument",
        action="store_true",
        default=False,
        required=False,
    )
    testing_args.add_argument(
        "-sn",
        "--signature-name",
        help="Run only one signature. To be used with --signature. Example -sig -sn cape_detected_threat",
        action="store",
        default=False,
        required=False,
    )
    testing_args.add_argument(
        "-jr",
        "--json-report",
        help="Path to json report, only if data not in mongo/default report location",
        action="store",
        default=False,
        required=False,
    )
    parser.add_argument(
        "--disable-memory-limit",
        help="Disable memory limit.",
        action="store_true",
        required=False,
        default=str_to_bool(os.getenv("CAPE_DISABLE_MEMORY_LIMIT", "false")),
    )
    parser.add_argument(
        "--engine",
        choices=["pebble", "prefork"],
        default="pebble",
        help="Processing engine: pebble (default, A/B control) or prefork.",
    )
    args = parser.parse_args()

    init_database()
    handlers = init_logging(debug=args.debug)
    init_modules()
    if args.id == "auto":
        autoprocess(
            parallel=args.parallel,
            failed_processing=args.failed_processing,
            maxtasksperchild=args.maxtasksperchild,
            memory_debugging=args.memory_debugging,
            processing_timeout=args.processing_timeout,
            debug=args.debug,
            disable_memory_limit=args.disable_memory_limit,
            engine=args.engine,
        )
    else:
        for start, end in args.id:
            for num in range(start, end + 1):
                set_formatter_fmt(num)
                log.debug("Processing task")
                if not path_exists(os.path.join(CUCKOO_ROOT, "storage", "analyses", str(num))):
                    log.error("Analysis folder doesn't exist anymore for Task #%d", num)
                    continue
                with db.session.begin():
                    task = db.view_task(num)
                    if task is None:
                        task = {"id": num, "target": None}
                        log.warning("Task not in database")
                    else:
                        # Add sample lookup as we point to sample from TMP. Case when delete_original=on
                        if not path_exists(task.target):
                            samples = db.sample_path_by_hash(task_id=task.id)
                            for sample in samples:
                                if path_exists(sample):
                                    task.__setattr__("target", sample)
                                    break
                    # Make sure that SQLAlchemy doesn't auto-begin a new transaction the next time
                    # these objects are accessed.
                    db.session.expunge_all()

                if args.signatures:
                    report = False
                    results = _load_report(num)
                    if not results:
                        # fallback to json
                        report = os.path.join(CUCKOO_ROOT, "storage", "analyses", str(num), "reports", "report.json")
                        if not path_exists(report):
                            if args.json_report and path_exists(args.json_report):
                                report = args.json_report
                            else:
                                sys.exit(f"File {report} doesn't exist")
                        if report:
                            results = json.load(open(report))
                    if results is not None:
                        # If the "statistics" key-value pair has not been set by now, set it here
                        if "statistics" not in results:
                            results["statistics"] = {"signatures": []}
                        if isinstance(task, dict):
                            RunSignatures(task=task, results=results).run(args.signature_name)
                        else:
                            RunSignatures(task=task.to_dict(), results=results).run(args.signature_name)
                        # If you are only running a single signature, log that output
                        if args.signature_name and results["signatures"]:
                            log.info("Signature output: %s", results["signatures"][0])
                else:
                    process(
                        task=task,
                        report=args.report,
                        capeproc=args.caperesubmit,
                        memory_debugging=args.memory_debugging,
                        debug=args.debug,
                    )
                log.debug("Finished processing task")
                set_formatter_fmt()

    for handler in handlers:
        if not handler:
            continue
        log.removeHandler(handler)


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main()
