on:
  push:
    branch:
      - master

name: Test build of cape2.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod a+x "${GITHUB_WORKSPACE}/installer/cape2.sh"
         BUILD_ENV=1 "${GITHUB_WORKSPACE}/installer/cape2.sh" base
      shell: bash
