name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run unit tests
        run: python -m pytest --import-mode=append tests/
